export const ERROR_MESSAGES = {
    ALL_FIELDS_REQUIRED: 'All Fields are required',
    EMAIL_OR_USERNAME_EXISTS: 'Email or Username already exists',
    EMAIL_AND_PASSWORD_REQUIRED: 'Email and Password are required',
    USER_NOT_FOUND: 'User not found',
    INVALID_CREDENTIALS: 'Invalid Credentials',
    UNAUTHORIZED_TOKEN_NOT_FOUND: 'Unauthorized - Token not found',
    TOKEN_NOT_FOUND: 'Token not found',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    UNAUTHORIZED_USER: 'Unauthorized - User not found',
    FORBIDDEN_ROLE: 'Forbidden - User does not have the required role',
    TOKEN_NOT_FOUND_OR_EXPIRED: 'Unauthorized - Token not found or expired',
    TOKEN_MISMATCH: 'Unauthorized - Token mismatch',
    INVALID_TOKEN: 'Unauthorized - Invalid token',
    SOMETHING_ERROR: 'Something went wrong',
    INVALID_TASK_ID: 'Invalid Task ID',
    TASK_NOT_FOUND: 'Task not found',
    INVALID_STATUS_ID: 'Invalid status ID',
     NO_TASKS_FOUND_TO_DELETE: 'No tasks found to delete.',
     STATUS_NOT_FOUND: 'Status not found',
     TASK_ID_REQUIRED: 'Task ID is required',
     TASKS_FETCHED_SUCCESSFULLY:'Tasks fetched successfully',
     SUB_TASK_NOT_FOUND: 'Subtask not found',
     FORBIDDEN_ACCESS: 'You do not  have permission to access this',
     NO_SHARED_TASKS_FOUND: 'No shared tasks found',
     MISSING_TASK_ID_OR_USER_ID: 'Missing task ID or user ID',
     INVALID_TASK_ID_FORMAT: 'Invalid task ID format',
     REMINDER_NOT_FOUND: 'Reminder not found'
     
  };
  
  export const SUCCESS_MESSAGES = {
    USER_REGISTERED_SUCCESSFULLY: 'User Registered successfully',
    USER_LOGIN_SUCCESSFULLY: 'User Login Successfully',
    USER_LOGOUT_SUCCESSFULLY: 'User Logout Successfully',
    TASK_CREATED_SUCCESSFULLY: 'Task created successfully',
    TASK_UPDATED_SUCCESSFULLY: 'Task updated successfully',
    TASK_DELETED_SUCCESSFULLY: 'Task deleted successfully',
    TASKS_RETRIEVED_SUCCESSFULLY: 'Tasks Retrieved Successfully',
    SUBTASK_UPDATED_SUCCESSFULLY: 'Status updated successfully',
    SUBTASK_CREATED_SUCCESSFULLY: 'Status created successfully',
    SUBTASK_DELETED_SUCCESSFULLY: 'Status deleted successfully',
    SUBTASK_RETRIEVED_SUCCESSFULLY: 'Statuses retrieved successfully',
    SUBTASK_ASSIGNED_SUCCESSFULLY: 'Task assigned successfully',
    TASK_STATUS_UPDATED_SUCCESSFULLY: 'Task status updated successfully',
    TASK_DUE_DATE_SET_SUCCESSFULLY: 'Task due date set successfully',
    TASK_SHARED_SUCCESSFULLY: 'Task shared successfully',
    TASK_MOVED_SUCCESSFULLY: 'Task moved successfully',
    TASK_FILTERED_SUCCESSFULLY: 'Tasks filtered successfully',
    TASK_ASSIGNED_SUCCESSFULLY: 'Task assigned successfully',
    REMINDER_CREATED: 'Reminder created successfully',
    REMINDER_UPDATED: 'Reminder updated successfully',
  };